image: Visual Studio 2019
version: 1.0.{build}
build_script:
  - cmd: C:\Python36-x64\python.exe BuildScript.py
after_build:
- cmd: C:\Python36-x64\python.exe BuildScript.py
artifacts:
- path: CygwinPortable*.7z
- path: CygwinPortable*.exe
